<?php
// This script and data application were generated by AppGini 23.17
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Campaigns.php');
	include_once(__DIR__ . '/Campaigns_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Campaigns');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Campaigns';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Campaigns`.`ID`" => "ID",
		"`Campaigns`.`CampaignName`" => "CampaignName",
		"DATE_FORMAT(`Campaigns`.`StartDate`, '%h:%i %p')" => "StartDate",
		"DATE_FORMAT(`Campaigns`.`EndDate`, '%h:%i %p')" => "EndDate",
		"CONCAT('$', FORMAT(`Campaigns`.`Goal`, 2))" => "Goal",
		"DATE_FORMAT(`Campaigns`.`DateClosed`, '%h:%i %p')" => "DateClosed",
		"`Campaigns`.`Status`" => "Status",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Campaigns`.`ID`',
		2 => 2,
		3 => '`Campaigns`.`StartDate`',
		4 => '`Campaigns`.`EndDate`',
		5 => '`Campaigns`.`Goal`',
		6 => '`Campaigns`.`DateClosed`',
		7 => 7,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Campaigns`.`ID`" => "ID",
		"`Campaigns`.`CampaignName`" => "CampaignName",
		"DATE_FORMAT(`Campaigns`.`StartDate`, '%h:%i %p')" => "StartDate",
		"DATE_FORMAT(`Campaigns`.`EndDate`, '%h:%i %p')" => "EndDate",
		"CONCAT('$', FORMAT(`Campaigns`.`Goal`, 2))" => "Goal",
		"DATE_FORMAT(`Campaigns`.`DateClosed`, '%h:%i %p')" => "DateClosed",
		"`Campaigns`.`Status`" => "Status",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Campaigns`.`ID`" => "ID",
		"`Campaigns`.`CampaignName`" => "Campaign Name",
		"`Campaigns`.`StartDate`" => "Start Date",
		"`Campaigns`.`EndDate`" => "End Date",
		"`Campaigns`.`Goal`" => "Goal",
		"`Campaigns`.`DateClosed`" => "Date Closed",
		"`Campaigns`.`Status`" => "Status",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Campaigns`.`ID`" => "ID",
		"`Campaigns`.`CampaignName`" => "CampaignName",
		"DATE_FORMAT(`Campaigns`.`StartDate`, '%h:%i %p')" => "StartDate",
		"DATE_FORMAT(`Campaigns`.`EndDate`, '%h:%i %p')" => "EndDate",
		"CONCAT('$', FORMAT(`Campaigns`.`Goal`, 2))" => "Goal",
		"DATE_FORMAT(`Campaigns`.`DateClosed`, '%h:%i %p')" => "DateClosed",
		"`Campaigns`.`Status`" => "Status",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`Campaigns` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Campaigns_view.php';
	$x->RedirectAfterInsert = 'Campaigns_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Campaigns';
	$x->TableIcon = 'resources/table_icons/32Px - 289.png';
	$x->PrimaryKey = '`Campaigns`.`ID`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 100, ];
	$x->ColCaption = ['Campaign Name', 'Start Date', 'End Date', 'Goal', 'Date Closed', 'Status', 'Donations', ];
	$x->ColFieldName = ['CampaignName', 'StartDate', 'EndDate', 'Goal', 'DateClosed', 'Status', '%Donations.CampaignID%', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, -1, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Campaigns_templateTV.html';
	$x->SelectedTemplate = 'templates/Campaigns_templateTVS.html';
	$x->TemplateDV = 'templates/Campaigns_templateDV.html';
	$x->TemplateDVP = 'templates/Campaigns_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Campaigns_init
	$render = true;
	if(function_exists('Campaigns_init')) {
		$args = [];
		$render = Campaigns_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Campaigns_header
	$headerCode = '';
	if(function_exists('Campaigns_header')) {
		$args = [];
		$headerCode = Campaigns_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Campaigns_footer
	$footerCode = '';
	if(function_exists('Campaigns_footer')) {
		$args = [];
		$footerCode = Campaigns_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
