<?php

// Data functions (insert, update, delete, form) for table Donations

// This script and data application were generated by AppGini 23.17
// Download AppGini for free from https://bigprof.com/appgini/download/

function Donations_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('Donations');
	if(!$arrPerm['insert']) return false;

	$data = [
		'DonationDate' => Request::dateComponents('DonationDate', ''),
		'Amount' => Request::val('Amount', ''),
		'Description' => Request::val('Description', ''),
		'SupporterID' => Request::lookup('SupporterID', ''),
		'CampaignID' => Request::lookup('CampaignID', ''),
		'Paytype' => Request::val('Paytype', ''),
		'Number' => Request::val('Number', ''),
		'TransNo' => Request::val('TransNo', ''),
		'Matching' => Request::checkBox('Matching', ''),
		'Anonymous' => Request::checkBox('Anonymous', ''),
		'Acknowledged' => Request::checkBox('Acknowledged', ''),
		'Notes' => br2nl(Request::val('Notes', '')),
		'MemoryOf' => Request::val('MemoryOf', ''),
		'HonorOf' => Request::val('HonorOf', ''),
	];

	if($data['Amount'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Amount': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Paytype'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Payment Type': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: Donations_before_insert
	if(function_exists('Donations_before_insert')) {
		$args = [];
		if(!Donations_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('Donations', backtick_keys_once($data), $error);
	if($error) {
		$error_message = $error;
		return false;
	}

	$recID = db_insert_id(db_link());

	update_calc_fields('Donations', $recID, calculated_fields()['Donations']);

	// hook: Donations_after_insert
	if(function_exists('Donations_after_insert')) {
		$res = sql("SELECT * FROM `Donations` WHERE `ID`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args = [];
		if(!Donations_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Donations', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(strlen(Request::val('SelectedID'))) Donations_copy_children($recID, Request::val('SelectedID'));

	return $recID;
}

function Donations_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function Donations_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('Donations', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Donations_before_delete
	if(function_exists('Donations_before_delete')) {
		$args = [];
		if(!Donations_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	// child table: MatchingFunds
	$res = sql("SELECT `ID` FROM `Donations` WHERE `ID`='{$selected_id}'", $eo);
	$ID = db_fetch_row($res);
	$rires = sql("SELECT COUNT(1) FROM `MatchingFunds` WHERE `DonationID`='" . makeSafe($ID[0]) . "'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'MatchingFunds', $RetMsg);
		return $RetMsg;
	} elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks) {
		$RetMsg = $Translation['confirm delete'];
		$RetMsg = str_replace('<RelatedRecords>', $rirow[0], $RetMsg);
		$RetMsg = str_replace('<TableName>', 'MatchingFunds', $RetMsg);
		$RetMsg = str_replace('<Delete>', '<input type="button" class="btn btn-danger" value="' . html_attr($Translation['yes']) . '" onClick="window.location = \'Donations_view.php?SelectedID=' . urlencode($selected_id) . '&delete_x=1&confirmed=1&csrf_token=' . urlencode(csrf_token(false, true)) . '\';">', $RetMsg);
		$RetMsg = str_replace('<Cancel>', '<input type="button" class="btn btn-success" value="' . html_attr($Translation[ 'no']) . '" onClick="window.location = \'Donations_view.php?SelectedID=' . urlencode($selected_id) . '\';">', $RetMsg);
		return $RetMsg;
	}

	sql("DELETE FROM `Donations` WHERE `ID`='{$selected_id}'", $eo);

	// hook: Donations_after_delete
	if(function_exists('Donations_after_delete')) {
		$args = [];
		Donations_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='Donations' AND `pkValue`='{$selected_id}'", $eo);
}

function Donations_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('Donations', $selected_id, 'edit')) return false;

	$data = [
		'DonationDate' => Request::dateComponents('DonationDate', ''),
		'Amount' => Request::val('Amount', ''),
		'Description' => Request::val('Description', ''),
		'SupporterID' => Request::lookup('SupporterID', ''),
		'CampaignID' => Request::lookup('CampaignID', ''),
		'Paytype' => Request::val('Paytype', ''),
		'Number' => Request::val('Number', ''),
		'TransNo' => Request::val('TransNo', ''),
		'Matching' => Request::checkBox('Matching', ''),
		'Anonymous' => Request::checkBox('Anonymous', ''),
		'Acknowledged' => Request::checkBox('Acknowledged', ''),
		'Notes' => br2nl(Request::val('Notes', '')),
		'MemoryOf' => Request::val('MemoryOf', ''),
		'HonorOf' => Request::val('HonorOf', ''),
	];

	if($data['Amount'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Amount': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['Paytype'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Payment Type': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('Donations', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: Donations_before_update
	if(function_exists('Donations_before_update')) {
		$args = ['old_data' => $old_data];
		if(!Donations_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'Donations', 
		backtick_keys_once($set), 
		['`ID`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="Donations_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('Donations', $data['selectedID'], calculated_fields()['Donations']);

	// hook: Donations_after_update
	if(function_exists('Donations_after_update')) {
		$res = sql("SELECT * FROM `Donations` WHERE `ID`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['ID'];
		$args = ['old_data' => $old_data];
		if(!Donations_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='Donations' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function Donations_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $separateDV = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;
	$eo = ['silentErrors' => true];
	$noUploads = null;
	$row = $urow = $jsReadOnly = $jsEditable = $lookups = null;

	$noSaveAsCopy = false;

	// mm: get table permissions
	$arrPerm = getTablePermissions('Donations');
	if(!$arrPerm['insert'] && $selected_id == '')
		// no insert permission and no record selected
		// so show access denied error unless TVDV
		return $separateDV ? $Translation['tableAccessDenied'] : '';
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if(strlen($selected_id) && Request::val('dvprint_x') != '') {
		$dvprint = true;
	}

	$filterer_SupporterID = Request::val('filterer_SupporterID');
	$filterer_CampaignID = Request::val('filterer_CampaignID');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: DonationDate
	$combo_DonationDate = new DateCombo;
	$combo_DonationDate->DateFormat = "mdy";
	$combo_DonationDate->MinYear = defined('Donations.DonationDate.MinYear') ? constant('Donations.DonationDate.MinYear') : 1900;
	$combo_DonationDate->MaxYear = defined('Donations.DonationDate.MaxYear') ? constant('Donations.DonationDate.MaxYear') : 2100;
	$combo_DonationDate->DefaultDate = parseMySQLDate('', '');
	$combo_DonationDate->MonthNames = $Translation['month names'];
	$combo_DonationDate->NamePrefix = 'DonationDate';
	// combobox: SupporterID
	$combo_SupporterID = new DataCombo;
	// combobox: CampaignID
	$combo_CampaignID = new DataCombo;
	// combobox: Paytype
	$combo_Paytype = new Combo;
	$combo_Paytype->ListType = 2;
	$combo_Paytype->MultipleSeparator = ', ';
	$combo_Paytype->ListBoxHeight = 10;
	$combo_Paytype->RadiosPerLine = 1;
	if(is_file(__DIR__ . '/hooks/Donations.Paytype.csv')) {
		$Paytype_data = addslashes(implode('', @file(__DIR__ . '/hooks/Donations.Paytype.csv')));
		$combo_Paytype->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions($Paytype_data))));
		$combo_Paytype->ListData = $combo_Paytype->ListItem;
	} else {
		$combo_Paytype->ListItem = array_trim(explode('||', entitiesToUTF8(convertLegacyOptions("Credit Card;;Check;;Cash;;Stock;;Stripe;;Benevity;;PayPal;;Wave;;Zelle"))));
		$combo_Paytype->ListData = $combo_Paytype->ListItem;
	}
	$combo_Paytype->SelectName = 'Paytype';
	$combo_Paytype->AllowNull = false;

	if($selected_id) {
		if(!check_record_permission('Donations', $selected_id, 'view'))
			return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = check_record_permission('Donations', $selected_id, 'edit');

		// can delete?
		$AllowDelete = check_record_permission('Donations', $selected_id, 'delete');

		$res = sql("SELECT * FROM `Donations` WHERE `ID`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'Donations_view.php', false);
		}
		$combo_DonationDate->DefaultDate = $row['DonationDate'];
		$combo_SupporterID->SelectedData = $row['SupporterID'];
		$combo_CampaignID->SelectedData = $row['CampaignID'];
		$combo_Paytype->SelectedData = $row['Paytype'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$filterField = Request::val('FilterField');
		$filterOperator = Request::val('FilterOperator');
		$filterValue = Request::val('FilterValue');
		$combo_SupporterID->SelectedData = $filterer_SupporterID;
		$combo_CampaignID->SelectedData = $filterer_CampaignID;
		$combo_Paytype->SelectedText = (isset($filterField[1]) && $filterField[1] == '7' && $filterOperator[1] == '<=>' ? $filterValue[1] : '');
	}
	$combo_SupporterID->HTML = '<span id="SupporterID-container' . $rnd1 . '"></span><input type="hidden" name="SupporterID" id="SupporterID' . $rnd1 . '" value="' . html_attr($combo_SupporterID->SelectedData) . '">';
	$combo_SupporterID->MatchText = '<span id="SupporterID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="SupporterID" id="SupporterID' . $rnd1 . '" value="' . html_attr($combo_SupporterID->SelectedData) . '">';
	$combo_CampaignID->HTML = '<span id="CampaignID-container' . $rnd1 . '"></span><input type="hidden" name="CampaignID" id="CampaignID' . $rnd1 . '" value="' . html_attr($combo_CampaignID->SelectedData) . '">';
	$combo_CampaignID->MatchText = '<span id="CampaignID-container-readonly' . $rnd1 . '"></span><input type="hidden" name="CampaignID" id="CampaignID' . $rnd1 . '" value="' . html_attr($combo_CampaignID->SelectedData) . '">';
	$combo_Paytype->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_SupporterID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['SupporterID'] : htmlspecialchars($filterer_SupporterID, ENT_QUOTES)); ?>"};
		AppGini.current_CampaignID__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['CampaignID'] : htmlspecialchars($filterer_CampaignID, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(SupporterID_reload__RAND__) == 'function') SupporterID_reload__RAND__();
				if(typeof(CampaignID_reload__RAND__) == 'function') CampaignID_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function SupporterID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#SupporterID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_SupporterID__RAND__.value, t: 'Donations', f: 'SupporterID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="SupporterID"]').val(resp.results[0].id);
							$j('[id=SupporterID-container-readonly__RAND__]').html('<span class="match-text" id="SupporterID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Supporters_view_parent]').hide(); } else { $j('.btn[id=Supporters_view_parent]').show(); }


							if(typeof(SupporterID_update_autofills__RAND__) == 'function') SupporterID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Donations', f: 'SupporterID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_SupporterID__RAND__.value = e.added.id;
				AppGini.current_SupporterID__RAND__.text = e.added.text;
				$j('[name="SupporterID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Supporters_view_parent]').hide(); } else { $j('.btn[id=Supporters_view_parent]').show(); }


				if(typeof(SupporterID_update_autofills__RAND__) == 'function') SupporterID_update_autofills__RAND__();
			});

			if(!$j("#SupporterID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_SupporterID__RAND__.value, t: 'Donations', f: 'SupporterID' },
					success: function(resp) {
						$j('[name="SupporterID"]').val(resp.results[0].id);
						$j('[id=SupporterID-container-readonly__RAND__]').html('<span class="match-text" id="SupporterID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Supporters_view_parent]').hide(); } else { $j('.btn[id=Supporters_view_parent]').show(); }

						if(typeof(SupporterID_update_autofills__RAND__) == 'function') SupporterID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_SupporterID__RAND__.value, t: 'Donations', f: 'SupporterID' },
				success: function(resp) {
					$j('[id=SupporterID-container__RAND__], [id=SupporterID-container-readonly__RAND__]').html('<span class="match-text" id="SupporterID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Supporters_view_parent]').hide(); } else { $j('.btn[id=Supporters_view_parent]').show(); }

					if(typeof(SupporterID_update_autofills__RAND__) == 'function') SupporterID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function CampaignID_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#CampaignID-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_CampaignID__RAND__.value, t: 'Donations', f: 'CampaignID' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="CampaignID"]').val(resp.results[0].id);
							$j('[id=CampaignID-container-readonly__RAND__]').html('<span class="match-text" id="CampaignID-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Campaigns_view_parent]').hide(); } else { $j('.btn[id=Campaigns_view_parent]').show(); }


							if(typeof(CampaignID_update_autofills__RAND__) == 'function') CampaignID_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'Donations', f: 'CampaignID' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_CampaignID__RAND__.value = e.added.id;
				AppGini.current_CampaignID__RAND__.text = e.added.text;
				$j('[name="CampaignID"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Campaigns_view_parent]').hide(); } else { $j('.btn[id=Campaigns_view_parent]').show(); }


				if(typeof(CampaignID_update_autofills__RAND__) == 'function') CampaignID_update_autofills__RAND__();
			});

			if(!$j("#CampaignID-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_CampaignID__RAND__.value, t: 'Donations', f: 'CampaignID' },
					success: function(resp) {
						$j('[name="CampaignID"]').val(resp.results[0].id);
						$j('[id=CampaignID-container-readonly__RAND__]').html('<span class="match-text" id="CampaignID-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Campaigns_view_parent]').hide(); } else { $j('.btn[id=Campaigns_view_parent]').show(); }

						if(typeof(CampaignID_update_autofills__RAND__) == 'function') CampaignID_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_CampaignID__RAND__.value, t: 'Donations', f: 'CampaignID' },
				success: function(resp) {
					$j('[id=CampaignID-container__RAND__], [id=CampaignID-container-readonly__RAND__]').html('<span class="match-text" id="CampaignID-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=Campaigns_view_parent]').hide(); } else { $j('.btn[id=Campaigns_view_parent]').show(); }

					if(typeof(CampaignID_update_autofills__RAND__) == 'function') CampaignID_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_clean());


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Donations_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Donations_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Donation Details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', (Request::val('Embedded') ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Donations_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Donations_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if(Request::val('Embedded')) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!Request::val('Embedded')) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate)
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Donations_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);

		if($AllowDelete)
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		else
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);

		// if not in embedded mode and user has insert only but no view/update/delete,
		// remove 'back' button
		if(
			$arrPerm['insert']
			&& !$arrPerm['update'] && !$arrPerm['delete'] && !$arrPerm['view']
			&& !Request::val('Embedded')
		)
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
		elseif($separateDV)
			$templateCode = str_replace(
				'<%%DESELECT_BUTTON%%>', 
				'<button
					type="submit" 
					class="btn btn-default" 
					id="deselect" 
					name="deselect_x" 
					value="1" 
					onclick="' . $backAction . '" 
					title="' . html_attr($Translation['Back']) . '">
						<i class="glyphicon glyphicon-chevron-left"></i> ' .
						$Translation['Back'] .
				'</button>',
				$templateCode
			);
		else
			$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '', $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#DonationDate').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#DonationDateDay, #DonationDateMonth, #DonationDateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Amount').replaceWith('<div class=\"form-control-static\" id=\"Amount\">' + (jQuery('#Amount').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Description').replaceWith('<div class=\"form-control-static\" id=\"Description\">' + (jQuery('#Description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#SupporterID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#SupporterID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#CampaignID').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#CampaignID_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('input[name=Paytype]').parent().html('<div class=\"form-control-static\">' + jQuery('input[name=Paytype]:checked').next().text() + '</div>')\n";
		$jsReadOnly .= "\tjQuery('#Number').replaceWith('<div class=\"form-control-static\" id=\"Number\">' + (jQuery('#Number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#TransNo').replaceWith('<div class=\"form-control-static\" id=\"TransNo\">' + (jQuery('#TransNo').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Matching').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Anonymous').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Acknowledged').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#Notes').replaceWith('<div class=\"form-control-static\" id=\"Notes\">' + (jQuery('#Notes').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#MemoryOf').replaceWith('<div class=\"form-control-static\" id=\"MemoryOf\">' + (jQuery('#MemoryOf').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#HonorOf').replaceWith('<div class=\"form-control-static\" id=\"HonorOf\">' + (jQuery('#HonorOf').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace(
		'<%%COMBO(DonationDate)%%>', 
		($selected_id && !$arrPerm['edit'] && ($noSaveAsCopy || !$arrPerm['insert']) ? 
			'<div class="form-control-static">' . $combo_DonationDate->GetHTML(true) . '</div>' : 
			$combo_DonationDate->GetHTML()
		), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(DonationDate)%%>', $combo_DonationDate->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(SupporterID)%%>', $combo_SupporterID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(SupporterID)%%>', $combo_SupporterID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(SupporterID)%%>', urlencode($combo_SupporterID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(CampaignID)%%>', $combo_CampaignID->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(CampaignID)%%>', $combo_CampaignID->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(CampaignID)%%>', urlencode($combo_CampaignID->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Paytype)%%>', $combo_Paytype->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Paytype)%%>', $combo_Paytype->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => ['parent table name', 'lookup field caption'] */
	$lookup_fields = ['SupporterID' => ['Supporters', 'Supporter'], 'CampaignID' => ['Campaigns', 'Campaign'], ];
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !Request::val('Embedded')*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-default add_new_parent" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus text-success"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(ID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DonationDate)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Amount)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Description)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(SupporterID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(CampaignID)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Paytype)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(TransNo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Matching)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Anonymous)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Acknowledged)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(DonationYear)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Notes)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(MemoryOf)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(HonorOf)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', safe_html($urow['ID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ID)%%>', html_attr($row['ID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode($urow['ID']), $templateCode);
		$templateCode = str_replace('<%%VALUE(DonationDate)%%>', app_datetime($row['DonationDate']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationDate)%%>', urlencode(app_datetime($urow['DonationDate'])), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Amount)%%>', safe_html($urow['Amount']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Amount)%%>', html_attr($row['Amount']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount)%%>', urlencode($urow['Amount']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Description)%%>', safe_html($urow['Description']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Description)%%>', html_attr($row['Description']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode($urow['Description']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(SupporterID)%%>', safe_html($urow['SupporterID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(SupporterID)%%>', html_attr($row['SupporterID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SupporterID)%%>', urlencode($urow['SupporterID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(CampaignID)%%>', safe_html($urow['CampaignID']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(CampaignID)%%>', html_attr($row['CampaignID']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CampaignID)%%>', urlencode($urow['CampaignID']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Paytype)%%>', safe_html($urow['Paytype']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Paytype)%%>', html_attr($row['Paytype']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Paytype)%%>', urlencode($urow['Paytype']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Number)%%>', safe_html($urow['Number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Number)%%>', html_attr($row['Number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Number)%%>', urlencode($urow['Number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(TransNo)%%>', safe_html($urow['TransNo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(TransNo)%%>', html_attr($row['TransNo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TransNo)%%>', urlencode($urow['TransNo']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Matching)%%>', ($row['Matching'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Anonymous)%%>', ($row['Anonymous'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Acknowledged)%%>', ($row['Acknowledged'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%VALUE(DonationYear)%%>', safe_html($urow['DonationYear']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationYear)%%>', urlencode($urow['DonationYear']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(Notes)%%>', safe_html($urow['Notes']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(Notes)%%>', safe_html($urow['Notes'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(Notes)%%>', urlencode($urow['Notes']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(MemoryOf)%%>', safe_html($urow['MemoryOf']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(MemoryOf)%%>', html_attr($row['MemoryOf']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MemoryOf)%%>', urlencode($urow['MemoryOf']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(HonorOf)%%>', safe_html($urow['HonorOf']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(HonorOf)%%>', html_attr($row['HonorOf']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HonorOf)%%>', urlencode($urow['HonorOf']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(ID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(DonationDate)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationDate)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Amount)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Amount)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Description)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Description)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(SupporterID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(SupporterID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(CampaignID)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(CampaignID)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Paytype)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Paytype)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(TransNo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(TransNo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(Matching)%%>', '', $templateCode);
		$templateCode = str_replace('<%%CHECKED(Anonymous)%%>', '', $templateCode);
		$templateCode = str_replace('<%%CHECKED(Acknowledged)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(DonationYear)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(DonationYear)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Notes)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Notes)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(MemoryOf)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(MemoryOf)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(HonorOf)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(HonorOf)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if(Request::val('dvprint_x') == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	$filterField = Request::val('FilterField');
	$filterOperator = Request::val('FilterOperator');
	$filterValue = Request::val('FilterValue');

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Donations');
	if($selected_id) {
		$jdata = get_joined_record('Donations', $selected_id);
		if($jdata === false) $jdata = get_defaults('Donations');
		$rdata = $row;
	}
	$templateCode .= loadView('Donations-ajax-cache', ['rdata' => $rdata, 'jdata' => $jdata]);

	// hook: Donations_dv
	if(function_exists('Donations_dv')) {
		$args = [];
		Donations_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}