<?php
// This script and data application were generated by AppGini 23.17
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/MatchingFunds.php');
	include_once(__DIR__ . '/MatchingFunds_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('MatchingFunds');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'MatchingFunds';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`MatchingFunds`.`ID`" => "ID",
		"`MatchingFunds`.`OrganizationName`" => "OrganizationName",
		"CONCAT('$', FORMAT(`MatchingFunds`.`Amount`, 2))" => "Amount",
		"IF(    CHAR_LENGTH(`Supporters1`.`LastName`) || CHAR_LENGTH(`Supporters1`.`MailingName`), CONCAT_WS('',   `Supporters1`.`LastName`, ', ', `Supporters1`.`MailingName`), '') /* SupporterID */" => "SupporterID",
		"DATE_FORMAT(`MatchingFunds`.`DateSubmitted`, '%h:%i %p')" => "DateSubmitted",
		"DATE_FORMAT(`MatchingFunds`.`DateReceived`, '%h:%i %p')" => "DateReceived",
		"`MatchingFunds`.`Notes`" => "Notes",
		"IF(    CHAR_LENGTH(`Donations1`.`ID`) || CHAR_LENGTH(`Donations1`.`Amount`), CONCAT_WS('',   `Donations1`.`ID`, ' - ', `Donations1`.`Amount`), '') /* DonationID */" => "DonationID",
		"`MatchingFunds`.`Attachment`" => "Attachment",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`MatchingFunds`.`ID`',
		2 => 2,
		3 => '`MatchingFunds`.`Amount`',
		4 => 4,
		5 => '`MatchingFunds`.`DateSubmitted`',
		6 => '`MatchingFunds`.`DateReceived`',
		7 => 7,
		8 => 8,
		9 => 9,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`MatchingFunds`.`ID`" => "ID",
		"`MatchingFunds`.`OrganizationName`" => "OrganizationName",
		"CONCAT('$', FORMAT(`MatchingFunds`.`Amount`, 2))" => "Amount",
		"IF(    CHAR_LENGTH(`Supporters1`.`LastName`) || CHAR_LENGTH(`Supporters1`.`MailingName`), CONCAT_WS('',   `Supporters1`.`LastName`, ', ', `Supporters1`.`MailingName`), '') /* SupporterID */" => "SupporterID",
		"DATE_FORMAT(`MatchingFunds`.`DateSubmitted`, '%h:%i %p')" => "DateSubmitted",
		"DATE_FORMAT(`MatchingFunds`.`DateReceived`, '%h:%i %p')" => "DateReceived",
		"`MatchingFunds`.`Notes`" => "Notes",
		"IF(    CHAR_LENGTH(`Donations1`.`ID`) || CHAR_LENGTH(`Donations1`.`Amount`), CONCAT_WS('',   `Donations1`.`ID`, ' - ', `Donations1`.`Amount`), '') /* DonationID */" => "DonationID",
		"`MatchingFunds`.`Attachment`" => "Attachment",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`MatchingFunds`.`ID`" => "ID",
		"`MatchingFunds`.`OrganizationName`" => "Organization Name",
		"`MatchingFunds`.`Amount`" => "Amount",
		"IF(    CHAR_LENGTH(`Supporters1`.`LastName`) || CHAR_LENGTH(`Supporters1`.`MailingName`), CONCAT_WS('',   `Supporters1`.`LastName`, ', ', `Supporters1`.`MailingName`), '') /* SupporterID */" => "SupporterID",
		"`MatchingFunds`.`DateSubmitted`" => "Date Submitted",
		"`MatchingFunds`.`DateReceived`" => "Date Received",
		"`MatchingFunds`.`Notes`" => "Notes",
		"IF(    CHAR_LENGTH(`Donations1`.`ID`) || CHAR_LENGTH(`Donations1`.`Amount`), CONCAT_WS('',   `Donations1`.`ID`, ' - ', `Donations1`.`Amount`), '') /* DonationID */" => "DonationID",
		"`MatchingFunds`.`Attachment`" => "Attachment",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`MatchingFunds`.`ID`" => "ID",
		"`MatchingFunds`.`OrganizationName`" => "OrganizationName",
		"CONCAT('$', FORMAT(`MatchingFunds`.`Amount`, 2))" => "Amount",
		"IF(    CHAR_LENGTH(`Supporters1`.`LastName`) || CHAR_LENGTH(`Supporters1`.`MailingName`), CONCAT_WS('',   `Supporters1`.`LastName`, ', ', `Supporters1`.`MailingName`), '') /* SupporterID */" => "SupporterID",
		"DATE_FORMAT(`MatchingFunds`.`DateSubmitted`, '%h:%i %p')" => "DateSubmitted",
		"DATE_FORMAT(`MatchingFunds`.`DateReceived`, '%h:%i %p')" => "DateReceived",
		"`MatchingFunds`.`Notes`" => "Notes",
		"IF(    CHAR_LENGTH(`Donations1`.`ID`) || CHAR_LENGTH(`Donations1`.`Amount`), CONCAT_WS('',   `Donations1`.`ID`, ' - ', `Donations1`.`Amount`), '') /* DonationID */" => "DonationID",
		"`MatchingFunds`.`Attachment`" => "Attachment",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['SupporterID' => 'SupporterID', 'DonationID' => 'DonationID', ];

	$x->QueryFrom = "`MatchingFunds` LEFT JOIN `Supporters` as Supporters1 ON `Supporters1`.`ID`=`MatchingFunds`.`SupporterID` LEFT JOIN `Donations` as Donations1 ON `Donations1`.`ID`=`MatchingFunds`.`DonationID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'MatchingFunds_view.php';
	$x->RedirectAfterInsert = 'MatchingFunds_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Matching Funds';
	$x->TableIcon = 'resources/table_icons/32Px - 396.png';
	$x->PrimaryKey = '`MatchingFunds`.`ID`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Organization Name', 'Amount', 'SupporterID', 'Date Submitted', 'Date Received', 'Notes', 'DonationID', 'Attachment', ];
	$x->ColFieldName = ['OrganizationName', 'Amount', 'SupporterID', 'DateSubmitted', 'DateReceived', 'Notes', 'DonationID', 'Attachment', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/MatchingFunds_templateTV.html';
	$x->SelectedTemplate = 'templates/MatchingFunds_templateTVS.html';
	$x->TemplateDV = 'templates/MatchingFunds_templateDV.html';
	$x->TemplateDVP = 'templates/MatchingFunds_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: MatchingFunds_init
	$render = true;
	if(function_exists('MatchingFunds_init')) {
		$args = [];
		$render = MatchingFunds_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: MatchingFunds_header
	$headerCode = '';
	if(function_exists('MatchingFunds_header')) {
		$args = [];
		$headerCode = MatchingFunds_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: MatchingFunds_footer
	$footerCode = '';
	if(function_exists('MatchingFunds_footer')) {
		$args = [];
		$footerCode = MatchingFunds_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
