<?php
// This script and data application were generated by AppGini 23.17
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/Notes.php');
	include_once(__DIR__ . '/Notes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('Notes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'Notes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`Notes`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Supporters1`.`MailingNameFull`), CONCAT_WS('',   `Supporters1`.`MailingNameFull`), '') /* Supporter Name */" => "SupporterID",
		"DATE_FORMAT(`Notes`.`Date`, '%c/%e/%Y %l:%i%p')" => "Date",
		"`Notes`.`Note`" => "Note",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`Notes`.`ID`',
		2 => '`Supporters1`.`MailingNameFull`',
		3 => '`Notes`.`Date`',
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`Notes`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Supporters1`.`MailingNameFull`), CONCAT_WS('',   `Supporters1`.`MailingNameFull`), '') /* Supporter Name */" => "SupporterID",
		"DATE_FORMAT(`Notes`.`Date`, '%c/%e/%Y %l:%i%p')" => "Date",
		"`Notes`.`Note`" => "Note",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`Notes`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Supporters1`.`MailingNameFull`), CONCAT_WS('',   `Supporters1`.`MailingNameFull`), '') /* Supporter Name */" => "Supporter Name",
		"`Notes`.`Date`" => "Date",
		"`Notes`.`Note`" => "Note",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`Notes`.`ID`" => "ID",
		"IF(    CHAR_LENGTH(`Supporters1`.`MailingNameFull`), CONCAT_WS('',   `Supporters1`.`MailingNameFull`), '') /* Supporter Name */" => "SupporterID",
		"DATE_FORMAT(`Notes`.`Date`, '%c/%e/%Y %l:%i%p')" => "Date",
		"`Notes`.`Note`" => "Note",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['SupporterID' => 'Supporter Name', ];

	$x->QueryFrom = "`Notes` LEFT JOIN `Supporters` as Supporters1 ON `Supporters1`.`ID`=`Notes`.`SupporterID` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'Notes_view.php';
	$x->RedirectAfterInsert = 'Notes_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Notes';
	$x->TableIcon = 'resources/table_icons/32Px - 125.png';
	$x->PrimaryKey = '`Notes`.`ID`';

	$x->ColWidth = [40, 20, 100, ];
	$x->ColCaption = ['Supporter Name', 'Date', 'Note', ];
	$x->ColFieldName = ['SupporterID', 'Date', 'Note', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/Notes_templateTV.html';
	$x->SelectedTemplate = 'templates/Notes_templateTVS.html';
	$x->TemplateDV = 'templates/Notes_templateDV.html';
	$x->TemplateDVP = 'templates/Notes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: Notes_init
	$render = true;
	if(function_exists('Notes_init')) {
		$args = [];
		$render = Notes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Notes_header
	$headerCode = '';
	if(function_exists('Notes_header')) {
		$args = [];
		$headerCode = Notes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: Notes_footer
	$footerCode = '';
	if(function_exists('Notes_footer')) {
		$args = [];
		$footerCode = Notes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
